### PR TITLE
migrate.go: add flag for SDK version

### LINKED ISSUE #10: SDK version should be a flag
I would make the sdk version an arg/flag so it can be forced to a particular version or `master` which is convenient in testing.

```
$ tf-sdk-migrator migrate -to master
```

### PR DESCRIPTION
**Pull request by kmoe**
fixes #10

### CODE REVIEW

**Review by radeksimko — CHANGES_REQUESTED** [review]
I'm not sure why but this patch seems to be breaking the case where user doesn't provide a path:

```
terraform-provider-cloudflare $ tf-sdk-migrator migrate
2019/08/30 17:00:32 /Users/radeksimko/gopath/src/github.com/terraform-providers/terraform-provider-cloudflare
Checking Go version used in provider...
2019/08/30 17:00:32 no Go version found in .go-version file for /Users/radeksimko/gopath/src: open /Users/radeksimko/gopath/src/.go-version: no such file or directory
2019/08/30 17:00:32 no go version found in go.mod file for /Users/radeksimko/gopath/src: open /Users/radeksimko/gopath/src/go.mod: no such file or directory
2019/08/30 17:00:32 no go version found in Travis config file for /Users/radeksimko/gopath/src: open /Users/radeksimko/gopath/src/.travis.yaml: no such file or directory
2019/08/30 17:00:32 failed to detect Go version for provider /Users/radeksimko/gopath/src
Go version does not satisfy constraint >=1.12. Found Go version: .
Checking whether provider uses Go modules...
2019/08/30 17:00:32 'go.mod' file not found - provider /Users/radeksimko/gopath/src is not using Go modules
Go modules not in use. Provider must use Go modules.
Checking version of github.com/hashicorp/terraform SDK used in provider...
SDK version does not satisfy constraint >=0.12.6. Found SDK version:
2019/08/30 17:00:32 Error getting SDK version for provider /Users/radeksimko/gopath/src: 2 errors occurred:
	* could not read go.mod file for provider /Users/radeksimko/gopath/src
	* could not read SDK version from go.mod file for provider/Users/radeksimko/gopath/src

Provider failed eligibility check for migration to the new SDK. Please see warnings above.
```

btw. it is possible to migrate providers (or rather dry-run the migration) without making the SDK public, e.g. via

```sh
git config --global url.ssh://git@github.com/.insteadOf https://github.com/
```

**Review by appilon — APPROVED** [review]
LGTM, I have not actually tested it out in a week or so myself so if we are certain the issues are solved then I think this is great! I can test it out later today too if we want more certainty.

**Review by radeksimko — COMMENTED** [review]
I'm afraid it still doesn't work for the "no argument" scenario:

```
$ tf-sdk-migrator migrate
2019/09/05 10:12:40 /Users/radeksimko/gopath/src/github.com/terraform-providers/terraform-provider-dns
2019/09/05 10:12:40 Error finding provider : Could not find  in working directory or GOPATH: /Users/radeksimko/go/1.12.9
```

**Review by radeksimko — APPROVED** [review]
LGTM, this looks and works great!

Thank you for taking it to the finish line.

**Pull request merged**
